# Generated by Django 4.2.25 on 2025-10-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('transfer', 'Transfer'), ('personal', 'Personal'), ('marketing', 'Marketing'), ('business', 'Business'), ('tax', 'Tax')], max_length=10),
        ),
    ]
