# Generated by Django 4.2.25 on 2025-10-16 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_category_category_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category_type', 'parent__name', 'name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='core.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('transfer', 'Transfer')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'parent', 'category_type')},
        ),
        migrations.RemoveField(
            model_name='category',
            name='team',
        ),
    ]
