# Generated by Django 4.2.25 on 2025-10-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='account',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Current balance in account currency (calculated, read-only)', max_digits=15),
        ),
        migrations.AddField(
            model_name='account',
            name='current_balance_pkr',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Current balance converted to PKR (calculated, read-only)', max_digits=15),
        ),
        migrations.AddField(
            model_name='account',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Opening balance when account was created (editable)', max_digits=15),
        ),
        migrations.AddField(
            model_name='account',
            name='opening_balance_pkr',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Opening balance converted to PKR', max_digits=15),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name='account',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='account',
            name='balance_pkr',
        ),
        migrations.RemoveField(
            model_name='account',
            name='team',
        ),
    ]
