# Generated by Django 4.2.25 on 2025-10-16 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_account_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='from_account',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='to_account',
        ),
        migrations.AddField(
            model_name='transaction',
            name='counter_party_account',
            field=models.ForeignKey(blank=True, help_text='Account to which money is transferred', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='core.account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='counter_party_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount credited to counter party account in their currency', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='counter_party_currency',
            field=models.ForeignKey(blank=True, help_text='Currency of counter party account for transfers', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counter_party_transactions', to='core.currency'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='counter_party_exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Exchange rate of counter party currency to PKR', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='Currency used for this transaction', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.currency'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='exchange_rate_to_pkr',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Exchange rate to PKR used on transaction date', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
