# Generated by Django 4.2.25 on 2025-10-19 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_transaction_from_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='team',
            field=models.ForeignKey(blank=True, help_text='Team for income/expense transactions (optional for transfers)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.team'),
        ),
    ]
