# Generated by Django 4.2.25 on 2025-10-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_transaction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount_pkr',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount converted to PKR', max_digits=15, null=True),
        ),
    ]
