# Generated by Django 4.2.25 on 2025-10-21 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_category_category_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='subcategory',
            field=models.ForeignKey(blank=True, help_text='Subcategory for expense transactions', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions_as_subcategory', to='core.category'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions_as_category', to='core.category'),
        ),
    ]
